### ISSUE TITLE
Human Readable - VCC Calculation Codes

### ISSUE THREAD

**Issue by kdjstudios** [kdjstudios/SABillingGitlab#761]
In GitLab by @kdjstudios on Mar 16, 2018, 10:56

Hello team,

It appears that on the Merge - Demo Site; that the VCC calculation codes are not displaying, they all show zero. While the actual billing file I can download does show actual values.  

Did we miss setting up something?

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Mar 19, 2018, 08:29

@kdjstudios 

The existing code was not working, thank's for bringing that up. Fixed on Merge and Production for VCC HR report.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Mar 19, 2018, 08:52

@smasih 

Thanks for the update. I will test again.

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Mar 20, 2018, 01:13

@tim.traylor 

reason the existing code was not working:

There were three loops required to get to amount displayed. So we kept it simple. 

Later in order to improve the speed we used mongo query for nested object. But, apparently rails orm doesn't respect that format and neither throws an error.

As, over the time our understanding toward's the system has improved so, we still managed to make it work with comparatively less number of loops.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Mar 20, 2018, 09:33

@smasih 

I just checked on Production and it is not working. Shows zero for all calculated codes.

I checked the HR on account: 075-00376

![image](/uploads/2f39de3a57dd7793dd4ba27558afac3b/image.png)

I can not even log into Merge

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Mar 21, 2018, 02:27

@kdjstudios 

It was fixed yesterday on merge and answernet production. Please try with some other billing cycle or account.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Mar 21, 2018, 09:27

@smasih 

I checked again, All Calculated codes are still not working on both Merge and Production.

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Mar 22, 2018, 05:14

@kdjstudios 

It's working just you were in the different billing cycle. We just added Billing Cycle name on to the billing cycle list in the HR report. (on ANSWERNET and MERGE)
![Screenshot](/uploads/f745f17a703a6eec0817b369a69d1669/Screenshot.png)

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Mar 22, 2018, 09:29

@smasih @pchaudhary @tim.traylor @rchauhan 

This is still not working. 

Account: Acupuncture Center - 0699

Export data from Answernet Production: [PreviewDataExportVCC.22March2018.csv](/uploads/d0de5a7a83a063a4abc42b06c406d8f3/PreviewDataExportVCC.22March2018.csv)

Export data from Answernet Merge: [PreviewDataExportVCC.22March2018__1_.csv](/uploads/3c76814bd19ad87d53ae7be7ba2f0e46/PreviewDataExportVCC.22March2018__1_.csv)

Columns B, C, and D should add up and then divided by 60 to equal column E....

 > (7006 + 7008 + 7017)/60


It appears only one VCC code is actually being calculated:

- As you should easily see, that even row 10 and row 11 should equal the same, but yet they do not?

![image](/uploads/62358720bf91d9955eb55a86ab152042/image.png)

**Please test, check, and validate your work before putting anything into an For-Approval status.**

**Comment by kdjstudios** [comment]
In GitLab by @pchaudhary on Mar 22, 2018, 23:39

assigned to @smasih

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Mar 23, 2018, 02:35

@kdjstudios 

I understand what you are trying to explain here, but as mentioned before in previous comments that **calculated fields section is getting its value from the invoices of that account within the selected billing cycle.**

So, only `VCC In Call Count` is selected as an activity on account unlike the `VCC In Call Agent`

The data in `Calculated Fields` section is being pulled from invoices of that account it's not getting calculated on the fly. 

![image](/uploads/244903500bb1a798ec214415d3060589/image.png)

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Mar 23, 2018, 03:47

@kdjstudios 

if it's needed to be calculated on fly, please create a new ticket.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Mar 23, 2018, 08:30

@smasih @tim.traylor 

This is the ticket to resolve this issue. 

- It does not need to be calculated on the fly, all of these values are calculated in the upload posting??

Almost all of the Calculated Codes do not display for all accounts on the HR report due to it not pulling from the RAW data as it was outlined to do when the HR report was developed. (As that is the whole point of this report!!!)

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Mar 26, 2018, 24:35

@kdjstudios 

I understand your concern Kyle, but we explained the same thing earlier and labeled it as it was.

Let's discuss it with Tim and do it if required. estimate 3-4 hr

**Comment by kdjstudios** [comment]
In GitLab by @tim.traylor on Mar 26, 2018, 06:02

This is correct - the codes/values should be calculated whether an item appears on an account's invoice or not.  So all usage, whether on a invoice or not, should be calculated and displayed here.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Mar 26, 2018, 08:54

@tim.traylor 

Thank you. 

@smasih 

Please reach out to us if you have any questions. This goes back to prior topics that were brought up, to not assume anything and to always ask.

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Jun 25, 2018, 04:51

@kdjstudios @tim.traylor 

we are going to start working on this, please let us know if there is something else which has higher priority.

`estimate required 7-9hr`

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Aug 21, 2018, 08:59

@smasih @pchaudhary 

Any updates on this?

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Sep 18, 2018, 08:04

@kdjstudios @pchaudhary @amishra @tim.traylor 

Tim's Approval required 

**Core Issue:** Calculated Fields should calculate values on the fly instead of pulling it from invoices.

**Implementation:** We need to create a mapping b/w report and 7xxx codes and we might need to work differently for each switch.

**Estimate:** Total estimate 7 hours  but the implementation is bit tricky so considering a buffer of another hour its `8 hours`

**Testing: ** 
    * Testing should be simple we need to check HR reports vs Invoice on that account for the same billing cycle.
    * repeat the same steps for all the switches.(eg: vcc, szeto, infinity, pinnacle)

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Sep 18, 2018, 08:04

changed time estimate to 1d

**Comment by kdjstudios** [comment]
In GitLab by @tim.traylor on Sep 18, 2018, 09:51

@smasih As we discussed, all of the calculated fields should be in the usage file, at least the first one that gets created during the posting.  The process that is generating the invoices should save ALL of the usage fields/values to the cdr_records collection.  This will allow the human readable to access the cdr data to display the info.

**Comment by kdjstudios** [comment]
In GitLab by @pchaudhary on Sep 19, 2018, 04:07

Hi [Tim] ( @tim.traylor ) & [Kyle] ( @kdjstudios ), 

We have reestimated the effort after the last tech call discussion & it's cut out to the `4 hours` 
including testing.

**Comment by kdjstudios** [comment]
In GitLab by @pchaudhary on Sep 19, 2018, 04:30

Hi [Tim] ( @tim.traylor ),   

We have successfully completed the development on this. We have also completed the testing on our end & we request to [Kyle] ( @kdjstudios ) to do the testing on his end as well, so if all goes well, we can put this on the ready state for the next release.  

**Developed**: We have developed the functionality to pull the calculated fields directly from the CDR Records collection which got generated while the file upload process to display on the HR.  

**Test Case**: 

* [x]  The `Calculated Values` column of the HR Report for the same billing cycle should have the values in Merge but not in Answernet. (On Answernet the column name is `Value from Invoice`)
* [x] The same value should be rendered in Preview report after the selected row.  
* [x] The same value should be in CSV export on the preview report section.

Hope this helps.

Thanks.

**Comment by kdjstudios** [comment]
In GitLab by @pchaudhary on Sep 19, 2018, 04:30

added 3h of time spent at 2018-09-19

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Sep 19, 2018, 08:40

@tim.traylor @pchaudhary @smasih @amishra 

Thanks for the update, yet you failed to update the labels on which server you developed and tested this. 

**MERGE2 testing: Failed**

1. Navigated to "5003 Prabhdeep Singh, MD, PLLC " account's HR
2. A few of the calculated fields are showing values, but most don't. Also some of them don't even have what their calculation is. Should we be opening a new ticket for this?

![image](/uploads/c557f64181e70573e13680f53f7e73bc/image.png)

**MERGE testing: Failed**

1. Navigated to "071-140 Surgical Associates, PSC" account's HR
2. It appears that the calculated fields are dislaying!!!! :+1: However, it would seem that the last two fields are not working. :-1: 

![image](/uploads/9b116a36b9d1e863fbd566d0b2118363/image.png)

It would seem that this error should have been spotted during the Aavaz Team's testing and I am wondering why it was not. Please elaborate.

**Comment by kdjstudios** [comment]
In GitLab by @pchaudhary on Sep 20, 2018, 07:04

Hi [Kyle] ( @kdjstudios ),  

> Thanks for the update, yet you failed to update the labels on which server you developed and tested this.

* Sorry for the inconvenience, we will keep in mind to update the testing label as well.  

We looked into this & below are our findings: 

* The missing information for code `55099` seems to be related with #1087 .
* The missing information for code `NC11` is because the code and the CDR firld of the activity is different.
  ![image](/uploads/67ed1e7a846b5c6685b19fb67c3ea52c/image.png)

> It would seem that this error should have been spotted during the Aavaz Team's testing and I am wondering why it was not. Please elaborate.

* We would like to tell you that we didn't traverse to every account report & the accounts which was tested by us are showing the information. It may be possible that these activities were not selected on those accounts. 

Thanks.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Sep 20, 2018, 08:39

@pchaudhary @tim.traylor 

Thanks for the update, I will keep wait until #1087 is fixed before retesting. 

Why would we be allowing the code and CDR field to be different int he first place? That in it self just sounds like asking for complaints, issues, and errors. 

In regards to: "We would like to tell you that we didn't traverse to every account report & the accounts which was tested by us are showing the information. It may be possible that these activities were not selected on those accounts."
- Are activities not set at the site level? not the account level. If we are changing something that effects multiple sites, accounts, etc. Then yes we should be testing them all. Example: If we just test this internally, then when it goes to our external clients who have different activities, etc. then there is a HUGE possibility it does not work because it was never fully tested. This is a prime situation of such example correct?

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Sep 24, 2018, 01:43

http://gitlab.aavaz.biz/AnswerNet/SABilling/issues/761#note_27153 updating estimate after discussion on tuesday

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Sep 24, 2018, 01:43

changed time estimate to 4h

**Comment by kdjstudios** [comment]
In GitLab by @pchaudhary on Sep 24, 2018, 04:52

Hi [Kyle] ( @kdjstudios ),  

We looked into the issue again & now we found the root cause due to which some of the columns are not showing the calculated values.  

* We have found that `55099` is not showing calculated values because the code is not activated when the usage of selected billing cycle was uploaded. ( Because we have added the code `55099` recently)  
* The code `NC11` is not showing the calculated values because the code is not VCC & the site should deactivate the code because now the site is being converted to the VCC.

Hope this helps. 

Marking for the testing for an approval.  

Thanks.

**Comment by kdjstudios** [comment]
In GitLab by @pchaudhary on Sep 24, 2018, 04:52

added 30m of time spent at 2018-09-24

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Sep 24, 2018, 11:25

@pchaudhary @smasih @tim.traylor 

Thank you for the update on why some of the columns were not working.

In regards to the 55099 code thanks for the clarification on why it would not be populating. I will retest on a new billing cycle to insure it is working. 

In regards to the NC11 code; it seems my questions above are still unanswered.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Sep 24, 2018, 11:46

Testing:

1. Logged into MERGE
2. Ran billing cycle on Demo Site with this usage file: [MERGE_DEMO_BILLING.csv](/uploads/8441f8097cbcaf8285e6dcbbeb2a6293/MERGE_DEMO_BILLING.csv)
3. Went into account DM-AC-9  and opened the HR report  
4. Only 3 of the calculated fields are displaying? It still looks like we are not showing the information from the CDR/uploaded resources file???

![image](/uploads/4ac48eeceaf6970d776729da11a1cd3a/image.png)
![image](/uploads/36196ca83febcd2ad4d9a9d968a324f1/image.png)


# NOTE: Why do we have a column header "Value from Invoice" ??
 - Nothing on this report should be pulling data from the invoice. This has been stated multiple times over the last three months. 


**Marking for discussion. There seems to still be miss understanding about what this report is.**

**Comment by kdjstudios** [comment]
In GitLab by @pchaudhary on Sep 25, 2018, 07:40

Hi [Kyle] ( @kdjstudios ),   

> In regards to the NC11 code; it seems my questions above are still unanswered.  
  >> Why would we be allowing the code and CDR field to be different in the first place? That in itself just sounds like asking for complaints, issues, and errors.  

* We do want to ensure that there is no issue to update the different Code & CDR field as the issue is because of the site has changed the switch.  

Thanks

**Comment by kdjstudios** [comment]
In GitLab by @pchaudhary on Sep 25, 2018, 07:45

Hi [Kyle] ( @kdjstudios ),   

We would like to confirm that the branch is not updated when you tested the same. I would like to mention that please test it today. The branch will stay live till tomorrow 03 Am EST.

Thanks.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Sep 25, 2018, 16:00

@pchaudhary @amishra @smasih @tim.traylor 

I was able to retest this. I ran another billing cycle for the Demo site on MERGE. After checking the HR report for Demo 54 account, all appears to be working and displaying in the HR report!

Marking for ready

**Comment by kdjstudios** [comment]
In GitLab by @pchaudhary on Sep 25, 2018, 23:04

assigned to @pchaudhary and unassigned @smasih

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Sep 25, 2018, 23:06

@pchaudhary 

please update the time spent

**Comment by kdjstudios** [comment]
In GitLab by @pchaudhary on Sep 26, 2018, 24:50

added 30m of time spent at 2018-09-26

**Comment by kdjstudios** [comment]
In GitLab by @pchaudhary on Sep 29, 2018, 03:59

Hi [Kyle]  ( @kdjstudios ), 

We have successfully released this to both of the production servers.

Thanks.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Sep 29, 2018, 13:05

@pchaudhary 

Thank you. I have just verified it is working for the Billings Site on Production.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Oct 12, 2018, 12:12

closed
